spring:
  datasource:
     platform: oracle
     url: jdbc:oracle:thin:@localhost:1521/orcl   
     username: system
     password: 123456
     driverClassName: oracle.jdbc.driver.OracleDriver
     max-active: 10
     max-idle: 5
     min-idle: 2
     initial-size: 6
     validation-query: select 1 from dual
     test-while-idle: true
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml

#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
